### ISSUE TITLE
Switch to Helm

### ISSUE THREAD

**Issue by pennersr** [Ecno92/dotemacs#1]
I have been a long-time ido user and forced myself to try Helm for a few days after noticing on https://emacs.zeef.com/ehartc that is far more popular. After my experiment I am fully converted: it's more popular for a reason ... (though be warned that your brain will shortcircuit a little when you start using it -- withdrawal symptoms).

**Comment by Ecno92** [comment]
Fixed in commit f380c4a8596160f9b1f16f0822a4096f1b908e93
